name = "status"
main = "./worker.js"
route = "status.l4c.workers.dev/*"
account_id = "9258d54908fd9bbb0e0de00aa4d1fbe0"
usage_model = "bundled"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-06-07"
kv_namespaces = [ 
    { binding = "STATUS", id = "e6e0763e45bd44f6abb0a9b0473c04ff", preview_id="e6e0763e45bd44f6abb0a9b0473c04ff" }
]

# [secrets]
# PTERO_API