name: Check service status
on:
  schedule:
    - cron: "3/5 * * * *"
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci --production
      - run: npm start
        env:
          NODE_ENV: PRODUCTION
          PTERO_HOST: ${{secrets.PTERO_HOST}}
          PTERO_KEY: ${{secrets.PTERO_KEY}}
      - run: npm run build
      - uses: actions-x/commit@v2